# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraID', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerID', models.PositiveIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=70)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('exdate', models.DateTimeField(verbose_name='exposure date')),
                ('shutterspeed', models.FloatField()),
                ('aperture', models.FloatField(default=2.8)),
                ('iso', models.IntegerField(default=100)),
                ('text', models.CharField(max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCam.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCam.Computer'),
        ),
    ]
